apiVersion: v1
kind: ConfigMap
metadata:
  name: drivecare-config
  namespace: drivecare
data:
  # Spring Boot Profile
  SPRING_PROFILES_ACTIVE: "dev"
  
  # Database URL - Choose one:
  # Option 1: Use local Kubernetes PostgreSQL
  # DB_URL: "jdbc:postgresql://postgres-service:5432/drivecare_db"
  # Option 2: Use DigitalOcean PostgreSQL (uncomment the line below and comment the line above)
  DB_URL: "jdbc:postgresql://db-postgresql-sgp1-83058-do-user-17134874-0.i.db.ondigitalocean.com:25061/defaultdb-pool?sslmode=require"
  
  # Frontend URL
  FRONTEND_URL: "http://localhost:5173"
  
  # Backend API URL for frontend
  VITE_API_URL: "http://localhost:30400/api"
  
  # Email configuration - Brevo
  MAIL_HOST: "smtp-relay.brevo.com"
  MAIL_PORT: "587"
  MAIL_PROTOCOL: "smtp"
  
  # OAuth2 Redirect URI
  OAUTH_FRONTEND_REDIRECT_URL: "http://localhost:5173"
  OAUTH2_REDIRECT_URI: "http://localhost:5173/oauth2/callback"
